services:
  - type: web
    name: i-like-pdf
    env: node
    repo: https://github.com/TimetrackerUD01/I-Like-PDF.git
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: GOOGLE_ADSENSE_CLIENT_ID
        value: ca-pub-1797172064583364
    healthCheckPath: /
    autoDeploy: true
    # Free plan - 750 hours/month = 24/7 coverage
    plan: free
